# Generated by Django 6.0.5 on 2026-05-23 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Awarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zgloszenia', models.DateTimeField(auto_now_add=True)),
                ('lokalizacja', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('priorytet', models.CharField(choices=[('niski', 'Niski'), ('sredni', 'Średni'), ('wysoki', 'Wysoki'), ('krytyczny', 'Krytyczny')], default='średni', max_length=20)),
                ('status', models.CharField(choices=[('nowe', 'Nowe'), ('w_realizacji', 'W realizacji'), ('zamkniete', 'Zamknięte')], default='nowe', max_length=20)),
                ('uwagi_technika', models.TextField(blank=True, null=True, verbose_name='Uwagi')),
                ('zglaszajacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Awaria',
                'verbose_name_plural': 'Awarie',
            },
        ),
    ]
